![Illustration of silhouetted heads](mentalhealth.jpg)

Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population, and that social connectedness (belonging to a social group) and acculturative stress (stress associated with joining a new culture) are predictive of depression.


Explore the `students` data using PostgreSQL to find out if you would come to a similar conclusion for international students and see if the length of stay is a contributing factor.

Here is a data description of the columns you may find helpful.

| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [25]:
-- Run this code to view the data in students
SELECT * 
FROM students;

    inter_dom region  gender  ... alone_bi  others_bi  internet_bi
0       Inter    SEA    Male  ...       No         No           No
1       Inter    SEA    Male  ...       No         No           No
2       Inter    SEA    Male  ...       No         No           No
3       Inter     EA  Female  ...       No         No           No
4       Inter     EA  Female  ...       No         No           No
..        ...    ...     ...  ...      ...        ...          ...
281                           ...
282                           ...
283                           ...
284                           ...
285                           ...

[286 rows x 50 columns]

Exploratory Queries to Check
- Do international students face more depression than domestic ones?
- Does length of stay reduce mental stress or depression?
- Does social connectedness protect against depression?
- How do language skills affect mental health?
- Are graduate students more stressed than undergraduates?
- Does gender play a role?
- Is acculturative stress a good predictor of depression?

In [26]:
-- Distribution of Student Types
SELECT inter_dom, COUNT(*) AS student_count
FROM students
WHERE inter_dom IS NOT NULL AND inter_dom != ''
GROUP BY inter_dom;

  inter_dom  student_count
0     Inter            201
1       Dom             67

In [27]:
-- Average Depression Score by Student Type
SELECT inter_dom, ROUND(AVG(todep),2) AS avg_depression
FROM students
WHERE inter_dom IS NOT NULL AND inter_dom != ''
GROUP BY inter_dom

  inter_dom  avg_depression
0     Inter            8.04
1       Dom            8.61

In [28]:
-- Depression vs Length of Stay
SELECT ROUND(stay) AS stay_year,
		ROUND(AVG(todep),2) AS avg_depression
FROM students
GROUP BY stay
ORDER BY stay_year;

   stay_year  avg_depression
0        1.0            7.70
1        2.0            8.58
2        3.0            8.87
3        4.0            7.96
4        5.0            7.67
5        6.0            6.00
6        7.0            4.00
7        8.0           10.00
8       10.0           13.00
9        NaN             NaN

In [29]:
-- Average Social Connectedness by Student Type
SELECT inter_dom, ROUND(AVG(tosc),2) AS avg_social_connectedness
FROM students
WHERE inter_dom IS NOT NULL AND inter_dom != ''
GROUP BY inter_dom;

  inter_dom  avg_social_connectedness
0     Inter                     37.42
1       Dom                     37.64

In [30]:
-- Average Acculturative Stress by Student Type
SELECT inter_dom, ROUND(AVG(toas),2) AS avg_acculturative_stress
FROM students
WHERE inter_dom IS NOT NULL AND inter_dom != ''
GROUP BY inter_dom;

  inter_dom  avg_acculturative_stress
0     Inter                     75.56
1       Dom                     62.84

In [31]:
-- Depression by Gender
SELECT gender, ROUND(AVG(todep),2) AS avg_depression
FROM students
	WHERE inter_dom IS NOT NULL AND inter_dom != ''
GROUP BY gender;

   gender  avg_depression
0  Female            8.40
1    Male            7.82

In [32]:
-- Relationship Between Social Connectedness and Depression
SELECT ROUND(tosc/10.0)*10 AS social_group,
        ROUND(AVG(todep),2) AS avg_depression
FROM students
WHERE tosc IS NOT NULL
GROUP BY social_group
ORDER BY social_group

   social_group  avg_depression
0            10           17.20
1            20           14.04
2            30            9.31
3            40            7.71
4            50            5.33

In [33]:
-- Impact of Japanese Language Proficiency on Acculturative Stress
SELECT japanese_cate, ROUND(AVG(toas),2) AS avg_acculturative_stress
FROM students
WHERE japanese_cate != ''
GROUP BY japanese_cate;

  japanese_cate  avg_acculturative_stress
0       Average                     75.36
1          High                     64.60
2           Low                     76.86

In [34]:
-- Impact of English Proficiency on Depression
SELECT english_cate, ROUND(AVG(todep),2) AS avg_depression
FROM students
WHERE english_cate IS NOT NULL AND english_cate != ''
GROUP BY english_cate;

  english_cate  avg_depression
0      Average            8.31
1         High            7.98
2          Low            9.32

In [35]:
-- Depression by Academic Level
SELECT academic, ROUND(AVG(todep),2) AS avg_depression
FROM students
	WHERE academic != ''
GROUP BY academic;

  academic  avg_depression
0    Under            8.43
1     Grad            5.29

In [36]:
-- Correlation Between Acculturative Stress and Depression
SELECT ROUND(toas/10.0)*10 AS acc_stress_group,
		ROUND(AVG(todep),2) AS avg_depression
FROM students
WHERE  toas IS NOT NULL
GROUP BY acc_stress_group
ORDER BY acc_stress_group;

    acc_stress_group  avg_depression
0                 40            6.08
1                 50            4.64
2                 60            6.43
3                 70            8.18
4                 80            9.40
5                 90            9.83
6                100           12.73
7                110            8.17
8                120            6.00
9                130           15.60
10               150            7.00

In [37]:
-- Age and Depression Relationship
SELECT age, ROUND(AVG(todep),2) AS avg_depression
FROM students
WHERE age IS NOT NULL
GROUP BY age
ORDER BY age;

    age  avg_depression
0    17            4.67
1    18            8.65
2    19            8.53
3    20            8.06
4    21            9.05
5    22            7.38
6    23            9.50
7    24            5.43
8    25            6.11
9    27           11.00
10   28            3.33
11   29            3.75
12   30            9.33
13   31            5.75